### ISSUE TITLE
add docker compose configuration

### ISSUE THREAD

**Issue by sanchitrk** [zyghq/zyg#12]
improve local dev setup by setting up docker configuration.

**Comment by sanchitrk** [comment]
I can think of a docker-compose configuration for setting up a few services like
- postgres
- redis
- etc

This will help in local dev setup and running the application locally.

**Comment by sushant102004** [comment]
Hi Sanchitrk,
Can I work on this issue?

**Comment by sanchitrk** [comment]
sure, go for it. let me know if you have any questions

**Comment by sushant102004** [comment]
Can you please give me format of .env?

**Comment by sanchitrk** [comment]
yes here's the env format
```POSTGRES_URI=""
SUPABASE_PROJECT_ID=""
SUPABASE_ANON_KEY=""
SUPABASE_JWT_SECRET=""
ZYG_CUSTOMER_JWT_SECRET=""
```
I am using [Neon DB](https://neon.tech/) - you can shoot up an instance for free if you want
Ideally, we should move to a local Postgres setup, I think docker should help here.

**Comment by sanchitrk** [comment]
@sushant102004 was this helpful? let me know if you need any assistance
